#  dev_location="West US" 
# dev_resource_group_name = "MyResourceGroup03" 
# dev_vnet_name = "myVnet"  
# dev_subnet_name = "mySubnet"
# dev_nsg_name = "myNSG"
# dev_vm_name = ["devVM1", "devVM2"]
# dev_admin_username =  "azureuser1"
# dev_admin_password = "admin@1234"
# dev_address_space = ["10.0.0.0/16"]
# dev_subnet_prefix = ["10.0.1.0/24"]
# dev_vm_size  = "Standard_DS1_v2"
# dev_computer_name  = "Mycomputername1"
# dev_allocation_method = "Dynamic"
# dev_public_ip_name = "devIP"
